export const metadata = {
  title: 'apeila.com | Online Shopping Store',
  description: 'Generated by apeila.com',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
