import { z } from 'zod';

export const productSchema = z.object({
  name: z.string().min(3, "Name must be at least 3 characters."),
  slug: z.string().min(3, "Slug must be at least 3 characters."),
  price: z.number().positive("Price must be positive."),
  oldPrice: z.number().optional(),
  discountPercentage: z.number().min(0).max(100).optional(),
  category: z.string().min(1, "Category is required."),
  subcategory: z.string().optional(),
  brand: z.string().optional(),
  stock: z.boolean().default(true),
  inStockCount: z.number().min(0).default(0),
  views: z.number().min(0).default(0),
  dateAdded: z.string().optional(),
  description: z.string().optional(),
  descriptionHTML: z.string().optional(),
  gallery: z.array(z.string()).optional(),
  colors: z.array(z.object({
    name: z.string(),
    code: z.string(),
    image: z.string().optional(),
  })).optional(),
  sizes: z.array(z.string()).optional(),
  shippingFee: z.number().min(0).optional(),
  soldBy: z.string().optional(),
  giftOption: z.boolean().optional(),
  isNew: z.boolean().optional(),
  isFeatured: z.boolean().optional(),
  tags: z.array(z.string()).optional(),
  seoMeta: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    keywords: z.array(z.string()).optional(),
  }).optional(),
  sku: z.string().optional(),
  barcode: z.string().optional(),
  specifications: z.record(z.any()).optional(),
  media: z.object({
    images: z.array(z.string()).optional(),
    videos: z.array(z.object({
      url: z.string(),
      type: z.string(),
      thumbnail: z.string().optional(),
      description: z.string().optional(),
    })).optional(),
  }).optional(),
  options: z.record(z.any()).optional(),
  reviewsSummary: z.record(z.any()).optional(),
  reviews: z.array(z.record(z.any())).optional(),
  audit: z.record(z.any()).optional(),
  returnPolicy: z.string().optional(),
  shipping: z.record(z.any()).optional(),
  availability: z.record(z.any()).optional(),
  customAttributes: z.record(z.any()).optional(),
  relatedProducts: z.array(z.string()).optional(),
  promotions: z.array(z.record(z.any())).optional(),
  bundleOptions: z.array(z.record(z.any())).optional(),
});
